MLP2DBYHARMONICG:
  lr: 0.001
  min_lr: 1.e-5
  lr_patience: 50
  lr_red_factoe: 0.8
  epochs: 60000
  lr_sch_epoch: 3000
  need_surgury: False
  weight_pde: 1.
  weight_dbc: 1.
  weight_nbc: 1.
  weight_compat: 1
  weight_u_guide: 0.
  weight_eps_guide: 0.

MLP2DBYHARMONICGUIDED:
  lr: 0.001
  min_lr: 1.e-5
  lr_patience: 50
  lr_red_factoe: 0.8
  epochs: 60000
  lr_sch_epoch: 3000
  need_surgury: True
  weight_pde: 1.
  weight_dbc: 1.
  weight_nbc: 1.
  weight_compat: 1
  weight_u_guide: 1.
  weight_eps_guide: 1.
  auxilary_task_params:
    u:
      method: jump
      offset_epoch: 5000
    eps:
      method: jump
      offset_epoch: 5000