MLP2DPOISSON:
  lr: 0.001
  min_lr: 1.e-6
  lr_patience: 50
  lr_red_factoe: 0.8
  epochs: 8000
  lr_sch_epoch: 2000

MLP1DPOISSONGUIDED:
  lr: 0.0005
  min_lr: 1.e-6
  lr_patience: 50
  lr_red_factoe: 0.92
  epochs: 25000
  lr_sch_epoch: 2000
  auxilary_task_params:
    method: stepwise
    offset_epoch: 5000
    reduction_factor: 2.
    step_size : 200