MLP2DPOISSON:
  lr: 0.001
  min_lr: 1.e-6
  lr_patience: 50
  lr_red_factoe: 0.95
  epochs: 10000
  lr_sch_epoch: 2000
  pde_weight: 1.
  bc_weight: 1.

# MLP2DPOISSONGUIDED:
#   lr: 0.001
#   min_lr: 1.e-6
#   lr_patience: 50
#   lr_red_factoe: 0.9
#   epochs: 10
#   lr_sch_epoch: 2000
#   auxilary_task_params:
#     method: stepwise
#     offset_epoch: 4000
#     reduction_factor: 1.05
#     step_size : 200

MLP2DPOISSONGUIDED1:
  lr: 0.001
  min_lr: 1.e-6
  lr_patience: 50
  lr_red_factoe: 0.95
  epochs: 10000
  lr_sch_epoch: 3000
  guide_weight: 1.
  pde_weight: 1.
  bc_weight: 1.
  auxilary_task_params:
    method: stepwise
    offset_epoch: 3000
    reduction_factor: 1.1
    step_size : 200

MLP2DPOISSONGUIDED2:
  lr: 0.001
  min_lr: 1.e-6
  lr_patience: 50
  lr_red_factoe: 0.95
  epochs: 20000
  lr_sch_epoch: 3000
  guide_weight: 1000.
  pde_weight: 1.
  bc_weight: 1.
  auxilary_task_params:
    method: stepwise
    offset_epoch: 3000
    reduction_factor: 1.1
    step_size : 200