MLP1DPOISSONTEACHER:
  lr: 0.001
  min_lr: 1.e-3
  lr_patience: 50
  lr_red_factoe: 0.9
  epochs: 5000
  lr_sch_epoch: 2000

MLP1DPOISSONSTUDENT:
  lr: 0.001
  min_lr: 5.e-4
  lr_patience: 50
  lr_red_factoe: 0.9
  epochs: 5000
  lr_sch_epoch: 2000