MLP1DPOISSONTEACHER:
  lr: 0.001
  min_lr: 1.e-3
  lr_patience: 50
  lr_red_factoe: 0.9
  epochs: 1000
  lr_sch_epoch: 2000
  pde_weight: 1.
  bc_weight: 1.
  compat_weight: 1.

MLP1DPOISSONSTUDENT:
  lr: 0.0001
  min_lr: 0.0005
  lr_patience: 50
  lr_red_factoe: 0.9
  epochs: 10000
  lr_sch_epoch: 2000
  pde_weight: 1.
  bc_weight: 1.
  compat_weight: 1.